import type { Metadata } from "next";
import { Playfair_Display, Red_Hat_Display } from "next/font/google";
import "../globals.css";
import Header from "./components/Header";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-play-fair",
});

const redHat = Red_Hat_Display({
  subsets: ["latin"],
  variable: "--font-red-hat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.className} ${playfair.variable} ${redHat.variable}`}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
